### ISSUE TITLE
this earns:

### ISSUE THREAD

**Issue by mubarizsaeed** [rhodyprog4ds/quickcheck#2]
this earns: 
-access level 2 and 3

this is **very** close on summarize an dvisualize level 3.  Revise this ntoebook for check 2 as describe to get those.

_Originally posted by @brownsarahm in https://github.com/rhodyprog4ds/portfolio-mubarizsaeed/pull/2#pullrequestreview-1350392340_

**Comment by brownsarahm** [comment]
This issue is posted in an inappropriate place.
